a=[21,54,85,76,98] #total elements 5
#The elements in Square bracket can be strings numbers alphabets. This is called list in python and arrays in MATLAB.

#IN_PYTHON_LOWEST_INDEX_POSITION_IS_ZERO

print(a[0]) #lowest/minimum index position element
print(a[-2]) #element of index position n-2=? that is 5-2=3 so the output will be element at position 3
print(a[0:3]) #elements from lowest index position to element 3
print(a[0:4]) #[:] This is called as range operator
print(a[1:3]) #the elements between 0 and 3 will be printed


#   EVERY PYTHON PROGRAM FILE NEED TO BE SAVED BEFORE RUNNING IT.
#   THE NAME SHOULD BE IN PROPER FORMAT NO USE OF KEYWORDS ALLWOED.
